/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvsIndexRouteImport } from './routes/tvs.index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as TvsSearchRouteImport } from './routes/tvs.search'
import { Route as TvsAiringTodayRouteImport } from './routes/tvs.airing-today'
import { Route as TvsAiringThisWeekRouteImport } from './routes/tvs.airing-this-week'
import { Route as PersonSearchRouteImport } from './routes/person.search'
import { Route as MoviesSearchRouteImport } from './routes/movies.search'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsIndexRoute = TvsIndexRouteImport.update({
  id: '/tvs/',
  path: '/tvs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsSearchRoute = TvsSearchRouteImport.update({
  id: '/tvs/search',
  path: '/tvs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsAiringTodayRoute = TvsAiringTodayRouteImport.update({
  id: '/tvs/airing-today',
  path: '/tvs/airing-today',
  getParentRoute: () => rootRouteImport,
} as any)
const TvsAiringThisWeekRoute = TvsAiringThisWeekRouteImport.update({
  id: '/tvs/airing-this-week',
  path: '/tvs/airing-this-week',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSearchRoute = PersonSearchRouteImport.update({
  id: '/person/search',
  path: '/person/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSearchRoute = MoviesSearchRouteImport.update({
  id: '/movies/search',
  path: '/movies/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recommendations': typeof RecommendationsRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies': typeof MoviesIndexRoute
  '/tvs': typeof TvsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recommendations': typeof RecommendationsRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies': typeof MoviesIndexRoute
  '/tvs': typeof TvsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recommendations': typeof RecommendationsRoute
  '/movies/search': typeof MoviesSearchRoute
  '/person/search': typeof PersonSearchRoute
  '/tvs/airing-this-week': typeof TvsAiringThisWeekRoute
  '/tvs/airing-today': typeof TvsAiringTodayRoute
  '/tvs/search': typeof TvsSearchRoute
  '/movies/': typeof MoviesIndexRoute
  '/tvs/': typeof TvsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preferences'
    | '/recommendations'
    | '/movies/search'
    | '/person/search'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies'
    | '/tvs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preferences'
    | '/recommendations'
    | '/movies/search'
    | '/person/search'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies'
    | '/tvs'
  id:
    | '__root__'
    | '/'
    | '/preferences'
    | '/recommendations'
    | '/movies/search'
    | '/person/search'
    | '/tvs/airing-this-week'
    | '/tvs/airing-today'
    | '/tvs/search'
    | '/movies/'
    | '/tvs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreferencesRoute: typeof PreferencesRoute
  RecommendationsRoute: typeof RecommendationsRoute
  MoviesSearchRoute: typeof MoviesSearchRoute
  PersonSearchRoute: typeof PersonSearchRoute
  TvsAiringThisWeekRoute: typeof TvsAiringThisWeekRoute
  TvsAiringTodayRoute: typeof TvsAiringTodayRoute
  TvsSearchRoute: typeof TvsSearchRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  TvsIndexRoute: typeof TvsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/': {
      id: '/tvs/'
      path: '/tvs'
      fullPath: '/tvs'
      preLoaderRoute: typeof TvsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/search': {
      id: '/tvs/search'
      path: '/tvs/search'
      fullPath: '/tvs/search'
      preLoaderRoute: typeof TvsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/airing-today': {
      id: '/tvs/airing-today'
      path: '/tvs/airing-today'
      fullPath: '/tvs/airing-today'
      preLoaderRoute: typeof TvsAiringTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvs/airing-this-week': {
      id: '/tvs/airing-this-week'
      path: '/tvs/airing-this-week'
      fullPath: '/tvs/airing-this-week'
      preLoaderRoute: typeof TvsAiringThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/search': {
      id: '/person/search'
      path: '/person/search'
      fullPath: '/person/search'
      preLoaderRoute: typeof PersonSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/search': {
      id: '/movies/search'
      path: '/movies/search'
      fullPath: '/movies/search'
      preLoaderRoute: typeof MoviesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreferencesRoute: PreferencesRoute,
  RecommendationsRoute: RecommendationsRoute,
  MoviesSearchRoute: MoviesSearchRoute,
  PersonSearchRoute: PersonSearchRoute,
  TvsAiringThisWeekRoute: TvsAiringThisWeekRoute,
  TvsAiringTodayRoute: TvsAiringTodayRoute,
  TvsSearchRoute: TvsSearchRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  TvsIndexRoute: TvsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
